service: serverless
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverlessUser
  region: us-east-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lex:*
      Resource: '*'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  tableName: recipes

functions:
  telegramToLex:
    handler: lambdas/endpoints/telegramToLex.handler
    events:
      - http:
          path: telegram_webhook
          method: POST
          cors: true

resources:
  Resources:
    MyDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
